name: casual_log_manager
description: "A simple dart package for application error and log management."
version: 0.2.2
repository: https://github.com/thecasualdev17/casual_log_manager.git
issue_tracker: https://github.com/thecasualdev17/casual_log_manager/issues

topics:
  - debugging
  - logging

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  logging: ">=1.1.1 <2.0.0"
  path_provider: ">=2.1.0 <3.0.0"
  stack_trace: ">=1.11.1 <=1.12.1"
  neat_periodic_task: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
  mockito: any
  test: any