name: log_manager
description: "A simple dart package for application error and log management."
version: 0.1.0
repository: https://github.com/thecasualdev17/log_manager.git

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  logging: ^1.3.0
  path_provider: ^2.1.5
  retry: ^3.1.2
  stack_trace: ^1.12.1
  neat_periodic_task: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: any
  test: any