# Flutter CI workflow inspired by quiver's dart ci.
name: Flutter CI

on:
  push:
    branches: [ "master", "develop", "**" ]
  pull_request:
    branches: [ "master", "develop" ]

env:
  PUB_ENVIRONMENT: bot.github

jobs:
  # Code Formating
  # Static Analysis
  analyze:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sdk: [ dev ]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603
        with:
          sdk: ${{ matrix.sdk }}
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.19.0
      - run: flutter --version
      - id: install
        name: Install dependencies
        run: flutter pub get
      - name: Check formatting
        run: dart format --output=none --set-exit-if-changed .
        if: always() && steps.install.outcome == 'success'

  # Testing
  test:
    needs: analyze
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        sdk: [ 3.7.2, dev ]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603
        with:
          sdk: ${{ matrix.sdk }}
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.19.0
      - run: flutter --version
      - id: install
        name: Install dependencies
        run: flutter pub get
      - name: Run VM tests
        run: flutter test
        if: always() && steps.install.outcome == 'success'
